baseUrl: http://practicalkombucha.com
languageCode: en-us
title: Practical Kombucha
theme: hugo-book
markup:
  tableOfContents:
    startLevel: 1
    stopLevel: 3
menu:
  after:
    - name: Brewing Log
      url: /posts/
      weight: 20
