baseUrl: http://vitusventure.github.io/practicalkombucha
languageCode: en-us
title: Practical Kombucha
theme: hugo-book
markup:
  tableOfContents:
    startLevel: 1
menu:
  after:
    - name: Brewing Log
      url: /posts/
      weight: 20
